// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace SARVA.Models;

public partial class Ciclo
{
    public int id { get; set; }

    public string id_usuario { get; set; }

    public int? id_empresa { get; set; }

    public string nome { get; set; }

    public DateTime? dataInicio { get; set; }

    public DateTime? dataFim { get; set; }

    public virtual ICollection<Produto> Produtos { get; set; } = new List<Produto>();

    public virtual Empresa Empresa { get; set; }
}