// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SARVA.Models;

public partial class Cliente
{
    public int id { get; set; }

    public string id_usuario { get; set; }

    public string nome { get; set; }

    public string email { get; set; }

    public DateTime? aniversario { get; set; }

    public int? scoreId { get; set; }

    public virtual ICollection<Venda> Venda { get; set; } = new List<Venda>();

    public virtual Score score { get; set; }
}