// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SARVA.Models;

public partial class Empresa
{
    public int id { get; set; }

    public string id_usuario { get; set; }

    public string razao_social { get; set; }

    public bool flag { get; set; }

    public virtual ICollection<Ciclo> Ciclos { get; set; } = new List<Ciclo>();

    public virtual ICollection<Pedido> Pedidos { get; set; } = new List<Pedido>();

    public virtual ICollection<Produto> Produtos { get; set; } = new List<Produto>();

    public virtual ICollection<Venda> Venda { get; set; } = new List<Venda>();
}