// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SARVA.Models;

public partial class Item_Venda
{
    public int codigo_produto { get; set; }

    public int id_ciclo_produto { get; set; }

    public int id_venda { get; set; }

    public decimal valor { get; set; }

    public int quantidade { get; set; }

    public DateTime? data_validade { get; set; }

    public virtual ICollection<Item_Pedido> Item_Pedido { get; set; } = new List<Item_Pedido>();

    public virtual Produto Produto { get; set; }

    public virtual Venda Venda { get; set; }
}