// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SARVA.Models;

public partial class Item_Pedido
{
    public int codigo_IV { get; set; }

    public int id_ciclo_IV { get; set; }

    public int id_venda_IV { get; set; }

    public int id_pedido { get; set; }

    public decimal valor { get; set; }

    public virtual Item_Venda Item_Venda { get; set; }

    public virtual Pedido Pedido { get; set; }
}