// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SARVA.Models;

public partial class Pedido
{
    public int id { get; set; }

    // Chave Estrangeira para o usuário.
    // O tipo 'string' corresponde ao tipo da chave primária do IdentityUser padrão.
    [Required]
    public string id_usuario { get; set; }

    // IMPORTANTE: Note que NÃO temos uma propriedade de navegação `public virtual IdentityUser Usuario { get; set; }`
    // porque a entidade IdentityUser pertence a outro DbContext. O EF Core não pode criar
    // um JOIN entre dois bancos de dados diferentes dessa forma. A ligação é puramente lógica.

    public int id_empresa { get; set; }

    public decimal? valor { get; set; }

    public DateTime data_pedido { get; set; }

    public DateTime data_vencimento { get; set; }

    public virtual ICollection<Item_Pedido> Item_Pedido { get; set; } = new List<Item_Pedido>();

    public virtual Empresa Empresa { get; set; }


}