// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SARVA.Models;

public partial class Produto
{
    public int id_ciclo { get; set; }

    public int codigo { get; set; }

    public string id_usuario { get; set; }

    public int id_empresa { get; set; }

    public string nome { get; set; }

    public decimal valor { get; set; }

    public int? pontos { get; set; }

    public bool flag { get; set; }

    public virtual ICollection<Item_Venda> Item_Venda { get; set; } = new List<Item_Venda>();

    public virtual Ciclo Ciclo { get; set; }

    public virtual Empresa Empresa { get; set; }
}