// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SARVA.Models;

public partial class Score
{
    public int id { get; set; }

    public string descricao { get; set; }

    public virtual ICollection<Cliente> Clientes { get; set; } = new List<Cliente>();
}