// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SARVA.Models;

public partial class Venda
{
    public int id { get; set; }

    public string id_usuario { get; set; }

    public int? id_cliente { get; set; }

    public int? id_empresa { get; set; }

    public decimal? valor { get; set; }

    public DateTime data_venda { get; set; }

    public DateTime data_vencimento { get; set; }

    public DateTime? data_pagamento { get; set; }

    public decimal? desconto { get; set; }

    public decimal? valorFinal { get; set; }

    public virtual ICollection<Item_Venda> Item_Venda { get; set; } = new List<Item_Venda>();

    public virtual Cliente Cliente { get; set; }

    public virtual Empresa Empresa { get; set; }
}